### ISSUE TITLE
Get wrong result when Join

### ISSUE THREAD

**Issue by Wen-He** [omnisci/omniscidb#466] opened 2019-12-20 08:23 UTC
I have two tables, `player_names` and `ejections`.
```
CREATE TABLE ejections (
ab_id BIGINT,
des TEXT ENCODING DICT(32),
event_num SMALLINT,
g_id INTEGER,
player_id INTEGER,
dayDate DATE ENCODING DAYS(32),
BS TEXT ENCODING DICT(32),
CORRECT TEXT ENCODING DICT(32),
team TEXT ENCODING DICT(32),
is_home_team BOOLEAN)
WITH (FRAGMENT_SIZE = 2000000)
```
```
CREATE TABLE player_names (
id INTEGER,
first_name TEXT ENCODING DICT(32),
last_name TEXT ENCODING DICT(32))
WITH (FRAGMENT_SIZE = 2000000)
```
The results of the following `SQL` queries are both `No rows returned.`.
```
SELECT * FROM player_names join ejections on player_names.id = ejections.player_id;
```
```
SELECT * FROM player_names, ejections WHERE player_names.id = ejections.player_id;
```
While the following two `SQL` queries return some rows.
```
omnisql> SELECT * FROM player_names where id = 444876;
id|first_name|last_name
444876|Alcides|Escobar
```
```
omnisql> SELECT * FROM ejections where player_id = 444876;
ab_id|des|event_num|g_id|player_id|dayDate|BS|CORRECT|team|is_home_team
2016171005|Kansas City Royals shortstop Alcides Escobar ejected by HP umpire Toby Basner.|359|201602242|444876|16-09-19|Y|C|kca|true
2015013668|Kansas City Royals shortstop Alcides Escobar ejected by HP umpire Greg Gibson.|518|201500181|444876|15-04-19|NULL|NULL|kca|true
2018084065|Kansas City Royals shortstop Alcides Escobar ejected by HP umpire Chad Fairchild.|484|201801100|444876|18-06-20|Y|C|kca|true
```

**Comment by alexbaden** [comment] 2019-12-20 19:39
Hi @Wen-He 

Thanks for the report. What version / commit hash were you running when this happened?

**Comment by Wen-He** [comment] 2019-12-21 04:22
At master `95b323e1` and `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=debug ..`

**Comment by alexbaden** [comment] 2019-12-27 18:13
Ok, thanks. We have been doing some work to reproduce this. Is it possible you inserted data into the table between running join queries? We cache CPU join hash tables on construction, but it appears there are some corner cases where the hash table needs to be invalidated / removed after the table has been modified. Can you try to reproduce the issue, but this time run `\clear_cpu` in `omnisql` after each `insert` / `drop` / `create` / `copy` table statement?

**Comment by Wen-He** [comment] 2019-12-29 12:31
I created tables and copied data before executing any query, and I didn't modify them after copying data. `\clear_cpu` didn't help.

BTW, Can I print/debug CPU join hash tables cache?

The two tables mentioned is `ejections` and `player_names` in [MLB Baseball Pitch Data (2015-2018)](https://www.kaggle.com/pschale/mlb-pitch-data-20152018)

**Comment by cdessanti** [comment] 2019-12-30 10:27
> 
> 
> I created tables and copied data before executing any query, and I didn't modify them after copying data. `\clear_cpu` didn't help.

> The two tables mentioned is `ejections` and `player_names` in [MLB Baseball Pitch Data (2015-2018)](https://www.kaggle.com/pschale/mlb-pitch-data-20152018)

I tried cloning the os repository today with your DDLs and the Mlb pitch data, with the master of  today, and I can't reproduce the issue; tried with both CPU and GPU, running join while loading data and after; no differences

```
omnisql> select count(*) from player_names join ejections on player_names.id = ejections.player_id;
EXPR$0
355
1 rows returned.
Execution time: 23 ms, Total time: 23 ms
omnisql>
omnisql> SELECT * FROM player_names, ejections WHERE player_names.id = ejections.player_id limit 10;
id|first_name|last_name|rowid|ab_id|des|event_num|g_id|player_id|dayDate|BS|CORRECT|team|is_home_team|rowid0
444468|Hector|Rondon|8|2015168383|Chicago Cubs pitcher Hector Rondon ejected by HP umpire Bruce Dreckman.|616|201502220|444468|15-09-19|NULL|NULL|chn|true|202
450308|Jered|Weaver|11|2015164249|Los Angeles Angels pitcher Jered Weaver ejected by HP umpire Brian O'Nora.|298|201502167|450308|15-09-16|NULL|NULL|laa|false|198
503285|Darren|O'Day|28|2018089082|Baltimore Orioles pitcher Darren O'Day ejected by HP umpire Stu Scheurwater.|578|201801165|503285|18-06-25|NULL|NULL|bal|true|661
518603|Justin|DeFratus|40|2015073043|Philadelphia Phillies pitcher Justin DeFratus ejected by HP umpire Lance Barksdale.|492|201500969|518603|15-06-16|NULL|NULL|phi|false|89
570649|Yordano|Ventura|45|2015012524|Kansas City Royals pitcher Yordano Ventura ejected by HP umpire Jim Joyce.|211|201500166|570649|15-04-18|NULL|NULL|kca|true|10
570649|Yordano|Ventura|45|2015017285|Kansas City Royals pitcher Yordano Ventura ejected by HP umpire Sam Holbrook.|423|201500229|570649|15-04-23|NULL|NULL|kca|false|20
570649|Yordano|Ventura|45|2016065777|Kansas City Royals pitcher Yordano Ventura ejected by 2B umpire Fieldin Culbreth.|362|201600866|570649|16-06-07|NULL|NULL|kca|false|281
502188|Jeff|Samardzija|46|2015017285|Chicago White Sox pitcher Jeff Samardzija ejected by HP umpire Sam Holbrook.|429|201500229|502188|15-04-23|NULL|NULL|cha|true|23
516969|Kelvin|Herrera|47|2015013668|Kansas City Royals pitcher Kelvin Herrera ejected by HP umpire Greg Gibson.|512|201500181|516969|15-04-19|NULL|NULL|kca|true|14
446372|Corey|Kluber|53|2016121655|Cleveland Indians pitcher Corey Kluber ejected by 1B umpire Jim Reynolds.|396|201601596|446372|16-08-03|NULL|NULL|cle|true|336
10 rows returned.
Execution time: 44 ms, Total time: 46 ms
```

I loaded tables with omnisql's copy command

**Comment by Wen-He** [comment] 2019-12-30 14:32
I have found the reason. I turned on the option `ENABLE_CUDA_KERNEL_DEBUG` in `CMakeLists.txt`. If I undo this modification, the join run as expected.

**Comment by alexbaden** [comment] 2020-04-16 20:22
Sounds like a possible compilation issue. Glad to hear you resolved it. 

Note that we've also fixed some edge cases recently that could give incorrect results on multi-step join queries in a multi-user env (e6d490a5dcc5f7530394a397388645d890fb2899) and resolved issues where the join cache was not purged when a table was modified (60f43f9567fe462400212e10367cc940ad651821). I'm going to close this but feel free to reopen if you encounter the issue again.

**Closed by alexbaden** 2020-04-16 20:22 UTC
